---

- name: Curl and check output
  block:
    - name: Curl content
      uri:
        url: "http://{{ app_fqdn }}"
        return_content: yes
      register: content
      failed_when: "'Jean-Philippe Lang' not in this.content"
    - name: Print content
      debug:
        msg: "{{ content }}"
  rescue:
    - name: Send notification message via Slack
      slack:
        token: "TFBPBNB2L/B01VDHYTS82/vVS6nZUI5NlJrEAjPcN6OoX2"
        channel: '#pr_baa'
        username: 'Ansible sender'
        msg: 'Rollback task: failed'
        icon_url: https://agardner.net/wp-content/uploads/2018/08/ansible-logo.png
        parse: 'full'
        

